# Generated by Django 4.0.2 on 2022-03-05 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subDeptart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subDname', models.CharField(max_length=50)),
                ('Dname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.dept')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=60)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('FamilyNo', models.IntegerField(null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Designation', models.CharField(max_length=61)),
                ('Cnic', models.IntegerField()),
                ('issueDate', models.DateField(null=True)),
                ('DateOfExpire', models.DateField(null=True)),
                ('nicCopy', models.ImageField(default='profile.JPEG', upload_to='nicCopy')),
                ('District', models.CharField(blank=True, max_length=150, null=True)),
                ('Province', models.CharField(blank=True, max_length=150, null=True)),
                ('Country', models.CharField(blank=True, max_length=150, null=True)),
                ('Address', models.CharField(blank=True, max_length=150, null=True)),
                ('pic', models.ImageField(default='profile.JPEG', upload_to='img')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('salery', models.IntegerField()),
                ('resign', models.BooleanField(default=False)),
                ('subDept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subdeptart')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'P'), ('A', 'A'), ('R', 'R')], max_length=30, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date(2022, 3, 5), null=True)),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee')),
                ('months_attendance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.attendance_month')),
                ('subd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subdeptart')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('emp', 'date'), name='unique_user_post'),
        ),
    ]
